services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: mobilab
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    #restart: always
    depends_on:
      - db
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
